# Generated initially using github-actions-wizard (https://github.com/cmdr2/github-actions-wizard)

name: CI Pipeline
run-name: CI Pipeline
on:
  release:
    types:
    - created
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Fetch ffmpeg static binaries for win and linux
      run: |-
        wget -q -O /tmp/ffmpeg-win64.zip https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-essentials.zip
        wget -q -O /tmp/ffmpeg-linux64.tar.xz https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz

        unzip -q /tmp/ffmpeg-win64.zip -d /tmp/ffmpeg_win64
        mkdir -p /tmp/ffmpeg_linux64
        tar -xf /tmp/ffmpeg-linux64.tar.xz -C /tmp/ffmpeg_linux64
    - name: Create the common build artifacts
      run: |-
        mkdir -p build_common/bin
        mkdir -p build_common/scripts

        cp -R screenrecorder LICENSE THIRD_PARTY_NOTICES.txt build_common/
        cp scripts/install.py build_common/scripts/
        cp requirements.txt build_common/scripts/
    - name: Create the Windows build
      run: |-
        cp -R build_common build_win64

        cp /tmp/ffmpeg_win64/ffmpeg-*-essentials_build/bin/ffmpeg.exe build_win64/bin/
        cp scripts/screenrecorder.cmd build_win64/

        cd build_win64
        zip -r ../screenrecorder-win-x86_64.zip .
    - name: Create the Linux build
      run: |-
        cp -R build_common build_linux64

        cp /tmp/ffmpeg_linux64/ffmpeg-*-amd64-static/ffmpeg build_linux64/bin/
        cp scripts/screenrecorder.sh build_linux64/

        cd build_linux64
        zip -r ../screenrecorder-linux-x86_64.zip .
    - name: Release
      uses: softprops/action-gh-release@v2
      if: github.ref_type == 'tag'
      with:
        files: |-
          screenrecorder-win-x86_64.zip
          screenrecorder-linux-x86_64.zip
